### ISSUE TITLE
Someone please guide me about how to use docker

### ISSUE THREAD

**Issue by semiangel** [pleaseworkibegyou/bankForThePoor#9]
ขอทางลัดเป็น article หรือ guide หรือ คู่มือ step-by-step ที่เข้าใจ docker ได้ภายในหน้าเดียว T^T

**Comment by krittakondev** [comment]
https://medium.com/touch-technologies/%E0%B8%97%E0%B8%B3%E0%B8%84%E0%B8%A7%E0%B8%B2%E0%B8%A1%E0%B8%A3%E0%B8%B9%E0%B9%89%E0%B8%88%E0%B8%B1%E0%B8%81-docker-compose-b6688fc98c6f

อันนี้ตัวสำหรับ docker-compose ครับ

**Comment by semiangel** [comment]
พอเข้าใจละ
